### ISSUE TITLE
Cannot import class

### ISSUE THREAD

**Issue by vladeha** [ec-blaster/pyMagicSwitchbot#1]
Hi,
I've got error, when tried to save your example as python script
Traceback (most recent call last):
  File "magicswitchbot.py", line 1, in <module>
    from magicswitchbot import MagicSwitchbot
  File "/home/pi/Python-3.5.2/magicswitchbot.py", line 1, in <module>
    from magicswitchbot import MagicSwitchbot
ImportError: cannot import name 'MagicSwitchbot' from 'magicswitchbot' (/home/pi/Python-3.5.2/magicswitchbot.py).
 
If I change it to "import magicswithbot" rather than "from magicswitchbot import MagicSwitchbot" , then I get another error 
   device = MagicSwitchbot(mac=MAC)
NameError: name 'MagicSwitchbot' is not defined.

**Comment by ec-blaster** [comment]
Could you show me your project's file structure?
How do you name your test program?

From the error you show, it appears that your test program's name is "magicswitchbot.py". Maybe Python is confusing the main program with the library. Try to rename the main program and do one of these options:

* Install the library with:
  ``` bash
  pip3 install pyMagicSwitchbot
  ```
* Clone the repository and create your main test program at the root of the clone. You must then have the following folder structure:
  ```
  <root>
    |
    +- magicswitchbot
    |       |
    |       +-- __init__.py
    +-- test.py
  ```
  In this case (if you don't use pip for the main library) you'll have to make sure you have `bluepy` installed as well. If you use the first option, pip will make charge of all dependencies.

I hope you can get it working with these instructions.

**Comment by vladeha** [comment]
Ok, It works! I did nothing, but rename script from magicswitchbot.py to test.py ) 
apparently name "magicswitchbot" somehow was confusing with the library, as you said!
Thank you! Now switchbot connected!
NFO:magicswitchbot:Connected to MagicSwitchbot at 34:14:B5:4B:2D:48
INFO:magicswitchbot:Auto-disconnect enabled after 30 seconds.

, but then I got another error

Traceback (most recent call last):
  File "test.py", line 12, in <module>
    res = device.get_battery()
  File "/usr/local/lib/python3.7/dist-packages/magicswitchbot/__init__.py", line 578, in get_battery
    ok = self._sendCommand(self.CMD_GETBAT, "01", self._retry_count)
  File "/usr/local/lib/python3.7/dist-packages/magicswitchbot/__init__.py", line 397, in _sendCommand
    go = self._auth(self._password)
TypeError: _auth() takes 1 positional argument but 2 were given
INFO:magicswitchbot:Client disconnected from 34:14:B5:4B:2D:48

**Comment by ec-blaster** [comment]
Make sure you have the latest code from the library.
If you are cloning it with git, run:

``` bash
$ git pull
```
 at the local working copy...
If you downloaded, make sure to download it again, the current `main` branch does not have that error.

**Comment by vladeha** [comment]
It's working now! Thank you

**Comment by ec-blaster** [comment]
You're welcome!
