### ISSUE TITLE
iobroker integration and error with test script

### ISSUE THREAD

**Issue by janhp** [ec-blaster/pyMagicSwitchbot#2]
dear dev,

thanks a lot for this great project so far.

I am new to python would love to use this script on my raspberry pi running ioBroker.

Is there a change that you develop an adapter for ioBroker?

While try to execute your test script I get the following error:
<img width="797" alt="Screenshot 2021-04-06 at 18 27 55" src="https://user-images.githubusercontent.com/71586781/113745765-e22a8480-9705-11eb-822c-088a4f925571.png">

**Comment by ec-blaster** [comment]
I think that you didn't install the component.

Are you running the `test.py` from the downloaded repository or did you install the module runing `pip3 install pyMagicSwitchbot`?

The module requires Python 3

**Comment by janhp** [comment]
I did install it with pip3 install. The test.py script is in the raspbian home folder. Now I get the following error: 
![image](https://user-images.githubusercontent.com/71586781/113845173-83145080-9795-11eb-80ec-f0576fdab692.png)

**Comment by ec-blaster** [comment]
It looks like there is a problem with the compiled version of the test program.

Maybe you tried to run it before with Python 2, maybe you edited the compiled version instead of the source...

Try to delete the `__pycache__` folder and try again. Make sure that the `test.py` is a valid source file, and in case you can read [this article](https://stackoverflow.com/questions/514371/whats-the-bad-magic-number-error) if it helps.

**Comment by janhp** [comment]
@ec-blaster thanks a lot! I removed the .py.save file not it seems to get to the next step: 
![image](https://user-images.githubusercontent.com/71586781/113852033-629bc480-979c-11eb-9405-f3078bb34de1.png)

Sorry for any inconvenience caused, I am a real python beginner.

**Comment by ec-blaster** [comment]
Ok, so now I think you found a bug! ;-)
I thought I had it fixed, I'll review it tonight and let you know.

PS: No inconvenience at all. We are all here to learn. I'm no Python magician either...

**Comment by ec-blaster** [comment]
You can check it now.
Update the library:

``` bash
pip3 install --upgrade pyMagicSwitchbot
```

After that, check that you have v1.0.12:

``` bash
$ pip3 list

Package            Version
------------------ ---------
...
pyMagicSwitchbot   1.0.12
...
```

Then run your program again.

**Comment by janhp** [comment]
awesome now it works!

**Comment by ec-blaster** [comment]
Congratulations!

Thanks for your help.
In relation to what you mentioned about iobroker, I'm sorry to tell you that I have no knowledge about it, and have no experience programming with NodeJS, so I hope you find someone who can help you with that. I developed a Home Assistant component, but that's Python.
