### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by janhp** [ec-blaster/pyMagicSwitchbot#3]
dear dev,

while trying to install your script I get the following error msg:
![image](https://user-images.githubusercontent.com/71586781/113751518-4fd9af00-970c-11eb-9cf1-64f5e1252184.png)

Can you please provide me some guidance? Thanks a lot!

**Comment by ec-blaster** [comment]
It appears you're trying to install the module with Python2, and it requires Python3. Read the issue #2

**Comment by ToracX** [comment]
I am having the exact same issue, I uninstalled everything and tried installing it using pip3, no succes.
