### ISSUE TITLE
Device (MagicSwitchbot) freezes after several fast connect->command->disconnect sequences

### ISSUE THREAD

**Issue by ezaton** [ec-blaster/pyMagicSwitchbot#4]
Hi.
Using your code example (attached for convenience), with a very minor modification (closing the connection when done), 
[magicswitchbot_test.txt](https://github.com/ec-blaster/pyMagicSwitchbot/files/6600352/magicswitchbot_test.txt) (this is txt suffix, but a Python code) in a fast sequence of waiting about 1-2 seconds between each run, the MagicSwitchbot stops responding. 
Actually - it requires a stop and start (long press on the button for about 10 seconds to stop, and same to start)

The logs show this:
**## Comment: Success:**
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Connected state: False
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Connecting using hci0 with 10 seconds timeout (1 of 3 retries)...
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Connected with hci0.
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Enabling notifications for userRead characteristic (000036f6-0000-1000-8000-00805f9b34fb). Handle: 0x28
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Client Characteristic Configuration Descriptor: 00002902-0000-1000-8000-00805f9b34fb. Handle: 0x29
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Notification handler initialized
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Characteristic notifications enabled: b'\x01\x00'
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Connected state: True
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Sending CMD_GETTOKEN command: 060100f6d60b0a45d7b9ca043457ee62
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Resetting received data
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Sending encrypted data: 7f95410768853e19babaee626220b602
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Data sent OK
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Waiting for notifications...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Encrypted data received: abfacb3acba91fbcb2e49beb3f3b95ac
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Unencrypted result: 060209ca7eeb7c010200070054922074
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Response: (Command = 06, Return Code = 02, Length = 9, Params = ca7eeb7c0102000700)
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] The current connection token is ca7eeb7c
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Chip type: 01, Firmware version: 2.0, Device type: 07, Password enabled: False
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Sending CMD_GETBAT command: 02010101ca7eeb7ca8867e18aeb2a149
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Resetting received data
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Sending encrypted data: 148b976e804d888a068ffddfe19bb5dd
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Data sent OK
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Waiting for notifications...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Encrypted data received: 45227883ecc1ee97b7cb63365ac6b19d
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Unencrypted result: 02020162f227eaec70e9d7b9d3fd1fb7
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Response: (Command = 02, Return Code = 02, Length = 1, Params = 62)
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Battery level: 98%
**## Commant: Success again**
Connected to device FC:45:C3:CB:56:AD with 98% of battery remaining
Turning on...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Connected state: True
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Sending CMD_SWITCH command: 05010101ca7eeb7c836fa01ec2074538
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Resetting received data
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Sending encrypted data: c4f57251d4dd15fc492574687a22bcc9
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Data sent OK
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Waiting for notifications...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Encrypted data received: e0de129859801bab097b1c150bc3cb26
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Unencrypted result: 05020100beb77fd62b8f5e4a5c9416ab
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Response: (Command = 05, Return Code = 02, Length = 1, Params = 00)
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Switch state changed successfully
    print("Could't get battery status")Turning off...
WARNING:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Unexpected response (ntfy) when checking connection state (1 of 3 attempts)
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Connected state: True
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Sending CMD_SWITCH command: 05010100ca7eeb7c9c9df577a42734cf
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Resetting received data
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Sending encrypted data: 9206e5e52ac703c322d435b2f3e7dbf8
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Data sent OK
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Waiting for notifications...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Encrypted data received: de3b580cf431eb6a53f8f82969950bdc
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Unencrypted result: 050201008cb175b594be9f24e5d1bdda
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Response: (Command = 05, Return Code = 02, Length = 1, Params = 00)
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Switch state changed successfully
Command executed successfully
Pushing...
WARNING:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Unexpected response (ntfy) when checking connection state (1 of 3 attempts)
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Connected state: True
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Sending CMD_SWITCH command: 05010102ca7eeb7c09d2bee178e210bb
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Resetting received data
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Sending encrypted data: edaa1582ebd028aec3cb0f63e6557763
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Data sent OK
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Waiting for notifications...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Encrypted data received: 645c3a1177616a7e4c36df369b28615b
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Unencrypted result: 05020100cdc28a08b5ad6955d03f6155
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Response: (Command = 05, Return Code = 02, Length = 1, Params = 00)
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Switch state changed successfully
Command executed successfully
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Disconnecting
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Connected state: True
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Client disconnected
**# Comment: This is where things don't go well**
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Disconnecting
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Connected state: False
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] The device was not connected
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Connected state: False
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Connecting using hci0 with 10 seconds timeout (1 of 3 retries)...
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Connected with hci0.
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Enabling notifications for userRead characteristic (000036f6-0000-1000-8000-00805f9b34fb). Handle: 0x28
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Client Characteristic Configuration Descriptor: 00002902-0000-1000-8000-00805f9b34fb. Handle: 0x29
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Notification handler initialized
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Characteristic notifications enabled: b'\x01\x00'
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Connected state: True
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Sending CMD_GETTOKEN command: 060100e07b4f689d6dbf184bddb7e108
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Resetting received data
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Sending encrypted data: 0d7e21cb9ae17ff36ee866d7845ceb9a
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Data sent OK
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Waiting for notifications...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Waiting...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Waiting...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Waiting...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Waiting...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Waiting...
**# Comment - about 5-10 minutes of no output at all**
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Encrypted data received: 9644edf526158ca164397ef0661e7cd9
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Unencrypted result: 0202016417cc3abe4bc553e23159c617
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Response: (Command = 02, Return Code = 02, Length = 1, Params = 64)
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Battery level: 100%
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Sending CMD_GETBAT command: 02010101329b1e613e573a7b032d560e
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Resetting received data
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Sending encrypted data: b81e8f86d757db460a45e5bb76748d35
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Data sent OK
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Waiting for notifications...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Encrypted data received: f36b3662c33c6734398e3d5ba484eb03
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Unencrypted result: 020201ffc141bd306c2fcf1d605ee79f
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Response: (Command = 02, Return Code = 02, Length = 1, Params = ff)
WARNING:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Communication failed. Remaining attempts: 3...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Connected state: True
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Connected state: True
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Sending CMD_GETTOKEN command: 060100f4b9f7bc7d9ad0b0c233409f5e
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Resetting received data
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Sending encrypted data: 769ed4abadb310db9270241ae6c61ae6
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Data sent OK
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Waiting for notifications...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Waiting...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Waiting...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Waiting...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Encrypted data received: 5b152ceb03cee7bc7f2f61a34a8a0578
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Unencrypted result: 0202016408fe9dd61f3d9197d3f397d3
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Response: (Command = 02, Return Code = 02, Length = 1, Params = 64)
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Battery level: 100%
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Sending CMD_GETBAT command: 020101010c6be9bece1ae6da06977396
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Resetting received data
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Sending encrypted data: 2bb47adf6820d7a4a79be996f186c737
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Data sent OK
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Waiting for notifications...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Encrypted data received: dcb7ee6fcd79ee7c23ab3f4b7e9a140e
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Unencrypted result: 020201ff4a92c10e11fdcb00e3f0b1a1
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Response: (Command = 02, Return Code = 02, Length = 1, Params = ff)
WARNING:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Communication failed. Remaining attempts: 2...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Connected state: True
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Connected state: True
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Sending CMD_GETTOKEN command: 0601002cc2939f868f9b91d3f5960701
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Resetting received data
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Sending encrypted data: 29251466081affeb6a8f2f321f31ee3e
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Data sent OK
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Waiting for notifications...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Waiting...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Waiting...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Waiting...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Encrypted data received: 2fd291f1b82660de9f4411794737e951
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Unencrypted result: 02020164a597bac6472a8a7f9a7ccb7b
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Response: (Command = 02, Return Code = 02, Length = 1, Params = 64)
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Battery level: 100%
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Sending CMD_GETBAT command: 02010101169e4f0c986bfacde8e65522
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Resetting received data
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Sending encrypted data: c3f20fcf72099c10c32a0c4420eab8a4
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Data sent OK
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Waiting for notifications...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Encrypted data received: c2bf5e759740d8f1b94972b062ca567a
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Unencrypted result: 020201ff646bf682b58c662e92cc1a0e
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Response: (Command = 02, Return Code = 02, Length = 1, Params = ff)
WARNING:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Communication failed. Remaining attempts: 1...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Connected state: True
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Connected state: True
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Sending CMD_GETTOKEN command: 060100026a9c685bd73f6d032ffa69cb
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Resetting received data
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Sending encrypted data: 8fc27a206f740a310adfef078b16d6a6
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Data sent OK
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Waiting for notifications...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Waiting...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Waiting...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Waiting...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Encrypted data received: a768cf220c3a0eea2fd576a8b3d18e51
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Unencrypted result: 020201644a41a77ca7dacab226a3e313
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Response: (Command = 02, Return Code = 02, Length = 1, Params = 64)
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Battery level: 100%
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Sending CMD_GETBAT command: 0201010138afaa83cd8f70e86691934d
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Resetting received data
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Sending encrypted data: c92f9db8db978e3c65ba580491bcb9c6
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Data sent OK
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Waiting for notifications...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Encrypted data received: 8be8d7825cd827eb73b69fc62d1a0134
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Unencrypted result: 020201ffbd01e8964f1c3a6e03161bb0
INFO:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Response: (Command = 02, Return Code = 02, Length = 1, Params = ff)
ERROR:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Communication failed. We won't try again.
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Disconnecting
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Connected state: False
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] The device was not connected
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Connected state: False
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Connecting using hci0 with 10 seconds timeout (1 of 3 retries)...
ERROR:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Couldn't connect to device (Timed out while trying to connect to peripheral FC:45:C3:CB:56:AD, addr type: public)
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Retrying in 1 seconds...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Connecting using hci0 with 10 seconds timeout (2 of 3 retries)...
ERROR:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Couldn't connect to device (Timed out while trying to connect to peripheral FC:45:C3:CB:56:AD, addr type: public)
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Retrying in 1 seconds...
DEBUG:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Connecting using hci0 with 10 seconds timeout (3 of 3 retries)...
ERROR:magicswitchbot:MagicSwitchbot[FC:45:C3:CB:56:AD] Couldn't connect to device (Failed to connect to peripheral FC:45:C3:CB:56:AD, addr type: public)
Could't get battery status

Firmware version 2.0, battery is (almost) fully charged, and the device is about 30 cm from the BT-equipped PC.
Also, following that - the device will not show in 'bluetoothctl scan on'

Any advice would be great. Thanks!

**Comment by ec-blaster** [comment]
Hi, @ezaton . Thanks for the feedback.

It's difficult to debug such a situation, but looking at your (excellent) logs, I came to find a bug when I check the connection status. I think I fixed it at the `dev` branch and you can [check it](https://github.com/ec-blaster/pyMagicSwitchbot/tree/dev) if you like.
Anyway, I'll keep investigating. It's true that seldom I find some "desynchronized" responses but I don't have many clues where it can get out from.

**Comment by ezaton** [comment]
Hi, and thank you for the very quick fix!
I think that a set of connect/disconnect commands in a fast sequence will cause the device to hang (not only the client script, but the device itself stops responding to any BT communication, including not appearing anymore in any BT/BLE scan). If I maintain a command frequency of once every 20+ seconds, the device remains responsive. Your fix (which works great) deals with the timeout handling for the device not responding. I wonder if we can contact (you/me, I don't care much) the manufacturer of the device (it is sold by many different vendors on Chinese sites) and bring this issue up, in order to get a firmware fix. 

Thanks for the fix!

**Comment by ec-blaster** [comment]
Hi.
Glad to hear it fixed it.
I indeed have a contact with the manufacturer, but they don't understand a word about Python or libraries in general.
To achieve they could be interested we must prove that the device fails just with the original android app...

**Comment by ezaton** [comment]
There is a slim chance we can reproduce it with the app. It requires a sequence of fast connect/disconnect sequences, however, the app remains connected for as long as it can, so little chance here.
Thanks!
