### ISSUE TITLE
Invalid Repository

### ISSUE THREAD

**Issue by ad1k4h** [ec-blaster/pyMagicSwitchbot#5]
Can't add repository into Hassio addons - https://github.com/ec-blaster/pyMagicSwitchbot

**Comment by ec-blaster** [comment]
Hello.

This is **not** a Hassio addon.
This is a Hass custom component, and the url you're looking for is [this one](https://github.com/ec-blaster/magicswitchbot-homeassistant).

Anyway, the component is in the default component list of HACS, you only have to install [HACS ](https://hacs.xyz/)and then look for MagicSwitchbot.

Bye.
